package com.player.mapper;

import com.player.model.VCollection;
import com.player.model.CollectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int countByExample(CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int deleteByExample(CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int deleteByPrimaryKey(String collecttionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int insert(VCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int insertSelective(VCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    List<VCollection> selectByExample(CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    VCollection selectByPrimaryKey(String collecttionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") VCollection record, @Param("example") CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByExample(@Param("record") VCollection record, @Param("example") CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKeySelective(VCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKey(VCollection record);
}