package com.player.mapper;

import com.player.model.Comments;
import com.player.model.CommentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int countByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int deleteByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int deleteByPrimaryKey(String commentsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int insert(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int insertSelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    List<Comments> selectByExampleWithBLOBs(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    List<Comments> selectByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    Comments selectByPrimaryKey(String commentsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") Comments record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Comments record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByExample(@Param("record") Comments record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKeySelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKey(Comments record);
}