package com.player.mapper;

import com.player.model.Feel;
import com.player.model.FeelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int countByExample(FeelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int deleteByExample(FeelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int deleteByPrimaryKey(String feelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int insert(Feel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int insertSelective(Feel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    List<Feel> selectByExampleWithBLOBs(FeelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    List<Feel> selectByExample(FeelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    Feel selectByPrimaryKey(String feelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") Feel record, @Param("example") FeelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Feel record, @Param("example") FeelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByExample(@Param("record") Feel record, @Param("example") FeelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKeySelective(Feel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Feel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feel
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKey(Feel record);
}