package com.player.mapper;

import com.player.model.reply;
import com.player.model.replyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface replyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int countByExample(replyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int deleteByExample(replyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int deleteByPrimaryKey(String replyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int insert(reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int insertSelective(reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    List<reply> selectByExampleWithBLOBs(replyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    List<reply> selectByExample(replyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    reply selectByPrimaryKey(String replyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") reply record, @Param("example") replyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") reply record, @Param("example") replyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByExample(@Param("record") reply record, @Param("example") replyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKeySelective(reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKey(reply record);
}