package com.player.mapper;

import com.player.model.Video;
import com.player.model.VideoExample;

public interface VideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int countByExample(VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int deleteByPrimaryKey(String videoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int insert(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int insertSelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    Video selectByPrimaryKey(String videoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKeySelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    int updateByPrimaryKey(Video record);
}