package com.player.model;

import java.util.Date;

public class Comments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.commentsId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String commentsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.videoId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String videoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.commentsTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Date commentstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.Attribute8
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.Attribute9
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.commentsContent
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String commentscontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.commentsId
     *
     * @return the value of t_comments.commentsId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getCommentsid() {
        return commentsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.commentsId
     *
     * @param commentsid the value for t_comments.commentsId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setCommentsid(String commentsid) {
        this.commentsid = commentsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.userId
     *
     * @return the value of t_comments.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.userId
     *
     * @param userid the value for t_comments.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.videoId
     *
     * @return the value of t_comments.videoId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getVideoid() {
        return videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.videoId
     *
     * @param videoid the value for t_comments.videoId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideoid(String videoid) {
        this.videoid = videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.commentsTime
     *
     * @return the value of t_comments.commentsTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Date getCommentstime() {
        return commentstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.commentsTime
     *
     * @param commentstime the value for t_comments.commentsTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setCommentstime(Date commentstime) {
        this.commentstime = commentstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.Attribute1
     *
     * @return the value of t_comments.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.Attribute1
     *
     * @param attribute1 the value for t_comments.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.Attribute2
     *
     * @return the value of t_comments.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.Attribute2
     *
     * @param attribute2 the value for t_comments.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.Attribute3
     *
     * @return the value of t_comments.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.Attribute3
     *
     * @param attribute3 the value for t_comments.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.Attribute4
     *
     * @return the value of t_comments.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.Attribute4
     *
     * @param attribute4 the value for t_comments.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.Attribute5
     *
     * @return the value of t_comments.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.Attribute5
     *
     * @param attribute5 the value for t_comments.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.Attribute6
     *
     * @return the value of t_comments.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.Attribute6
     *
     * @param attribute6 the value for t_comments.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.Attribute7
     *
     * @return the value of t_comments.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.Attribute7
     *
     * @param attribute7 the value for t_comments.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.Attribute8
     *
     * @return the value of t_comments.Attribute8
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute8() {
        return attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.Attribute8
     *
     * @param attribute8 the value for t_comments.Attribute8
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.Attribute9
     *
     * @return the value of t_comments.Attribute9
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute9() {
        return attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.Attribute9
     *
     * @param attribute9 the value for t_comments.Attribute9
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute9(String attribute9) {
        this.attribute9 = attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.commentsContent
     *
     * @return the value of t_comments.commentsContent
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getCommentscontent() {
        return commentscontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.commentsContent
     *
     * @param commentscontent the value for t_comments.commentsContent
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setCommentscontent(String commentscontent) {
        this.commentscontent = commentscontent;
    }
}