package com.player.model;

import java.util.Date;

public class Feel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.feelId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String feelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.videoId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String videoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.feelTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Date feeltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.Attribute8
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.Attribute9
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.Attribute10
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feel.showContent
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String showcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.feelId
     *
     * @return the value of t_feel.feelId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getFeelid() {
        return feelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.feelId
     *
     * @param feelid the value for t_feel.feelId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setFeelid(String feelid) {
        this.feelid = feelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.userId
     *
     * @return the value of t_feel.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.userId
     *
     * @param userid the value for t_feel.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.videoId
     *
     * @return the value of t_feel.videoId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getVideoid() {
        return videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.videoId
     *
     * @param videoid the value for t_feel.videoId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideoid(String videoid) {
        this.videoid = videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.feelTime
     *
     * @return the value of t_feel.feelTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Date getFeeltime() {
        return feeltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.feelTime
     *
     * @param feeltime the value for t_feel.feelTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setFeeltime(Date feeltime) {
        this.feeltime = feeltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.Attribute1
     *
     * @return the value of t_feel.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.Attribute1
     *
     * @param attribute1 the value for t_feel.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.Attribute2
     *
     * @return the value of t_feel.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.Attribute2
     *
     * @param attribute2 the value for t_feel.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.Attribute3
     *
     * @return the value of t_feel.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.Attribute3
     *
     * @param attribute3 the value for t_feel.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.Attribute4
     *
     * @return the value of t_feel.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.Attribute4
     *
     * @param attribute4 the value for t_feel.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.Attribute5
     *
     * @return the value of t_feel.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.Attribute5
     *
     * @param attribute5 the value for t_feel.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.Attribute6
     *
     * @return the value of t_feel.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.Attribute6
     *
     * @param attribute6 the value for t_feel.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.Attribute7
     *
     * @return the value of t_feel.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.Attribute7
     *
     * @param attribute7 the value for t_feel.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.Attribute8
     *
     * @return the value of t_feel.Attribute8
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute8() {
        return attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.Attribute8
     *
     * @param attribute8 the value for t_feel.Attribute8
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.Attribute9
     *
     * @return the value of t_feel.Attribute9
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute9() {
        return attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.Attribute9
     *
     * @param attribute9 the value for t_feel.Attribute9
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute9(String attribute9) {
        this.attribute9 = attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.Attribute10
     *
     * @return the value of t_feel.Attribute10
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute10() {
        return attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.Attribute10
     *
     * @param attribute10 the value for t_feel.Attribute10
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute10(String attribute10) {
        this.attribute10 = attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feel.showContent
     *
     * @return the value of t_feel.showContent
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getShowcontent() {
        return showcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feel.showContent
     *
     * @param showcontent the value for t_feel.showContent
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setShowcontent(String showcontent) {
        this.showcontent = showcontent;
    }
}