package com.player.model;

import java.util.Date;

public class reply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.replyId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String replyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.commentsId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String commentsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.replyTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Date replytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.revertId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String revertid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.replyContent
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String replycontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.replyId
     *
     * @return the value of t_reply.replyId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getReplyid() {
        return replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.replyId
     *
     * @param replyid the value for t_reply.replyId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setReplyid(String replyid) {
        this.replyid = replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.commentsId
     *
     * @return the value of t_reply.commentsId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getCommentsid() {
        return commentsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.commentsId
     *
     * @param commentsid the value for t_reply.commentsId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setCommentsid(String commentsid) {
        this.commentsid = commentsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.replyTime
     *
     * @return the value of t_reply.replyTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Date getReplytime() {
        return replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.replyTime
     *
     * @param replytime the value for t_reply.replyTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.userId
     *
     * @return the value of t_reply.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.userId
     *
     * @param userid the value for t_reply.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.revertId
     *
     * @return the value of t_reply.revertId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getRevertid() {
        return revertid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.revertId
     *
     * @param revertid the value for t_reply.revertId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setRevertid(String revertid) {
        this.revertid = revertid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.Attribute1
     *
     * @return the value of t_reply.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.Attribute1
     *
     * @param attribute1 the value for t_reply.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.Attribute2
     *
     * @return the value of t_reply.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.Attribute2
     *
     * @param attribute2 the value for t_reply.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.Attribute3
     *
     * @return the value of t_reply.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.Attribute3
     *
     * @param attribute3 the value for t_reply.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.Attribute4
     *
     * @return the value of t_reply.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.Attribute4
     *
     * @param attribute4 the value for t_reply.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.Attribute5
     *
     * @return the value of t_reply.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.Attribute5
     *
     * @param attribute5 the value for t_reply.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.Attribute6
     *
     * @return the value of t_reply.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.Attribute6
     *
     * @param attribute6 the value for t_reply.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.replyContent
     *
     * @return the value of t_reply.replyContent
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getReplycontent() {
        return replycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.replyContent
     *
     * @param replycontent the value for t_reply.replyContent
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setReplycontent(String replycontent) {
        this.replycontent = replycontent;
    }
}