package com.player.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userName
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.passWord
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.enableFlag
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String enableflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.regTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.modifyTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.isAdmin
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String isadmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.modifyPerson
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String modifyperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.nickName
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userSex
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String usersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userBirthday
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Date userbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userPhone
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String userphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userEmail
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String useremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userHobby
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String userhobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userSignature
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String usersignature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.headPortrait
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String headportrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.modifyAllTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Date modifyalltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.modifyAllPerson
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String modifyallperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userAge
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Integer userage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userScore
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Integer userscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.Attribute8
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute8;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userId
     *
     * @return the value of t_user.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userId
     *
     * @param userid the value for t_user.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userName
     *
     * @return the value of t_user.userName
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userName
     *
     * @param username the value for t_user.userName
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.passWord
     *
     * @return the value of t_user.passWord
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.passWord
     *
     * @param password the value for t_user.passWord
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.enableFlag
     *
     * @return the value of t_user.enableFlag
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getEnableflag() {
        return enableflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.enableFlag
     *
     * @param enableflag the value for t_user.enableFlag
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setEnableflag(String enableflag) {
        this.enableflag = enableflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.regTime
     *
     * @return the value of t_user.regTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.regTime
     *
     * @param regtime the value for t_user.regTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.modifyTime
     *
     * @return the value of t_user.modifyTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.modifyTime
     *
     * @param modifytime the value for t_user.modifyTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.isAdmin
     *
     * @return the value of t_user.isAdmin
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.isAdmin
     *
     * @param isadmin the value for t_user.isAdmin
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setIsadmin(String isadmin) {
        this.isadmin = isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.modifyPerson
     *
     * @return the value of t_user.modifyPerson
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getModifyperson() {
        return modifyperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.modifyPerson
     *
     * @param modifyperson the value for t_user.modifyPerson
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setModifyperson(String modifyperson) {
        this.modifyperson = modifyperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.nickName
     *
     * @return the value of t_user.nickName
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.nickName
     *
     * @param nickname the value for t_user.nickName
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userSex
     *
     * @return the value of t_user.userSex
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userSex
     *
     * @param usersex the value for t_user.userSex
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUsersex(String usersex) {
        this.usersex = usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userBirthday
     *
     * @return the value of t_user.userBirthday
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Date getUserbirthday() {
        return userbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userBirthday
     *
     * @param userbirthday the value for t_user.userBirthday
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUserbirthday(Date userbirthday) {
        this.userbirthday = userbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userPhone
     *
     * @return the value of t_user.userPhone
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userPhone
     *
     * @param userphone the value for t_user.userPhone
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userEmail
     *
     * @return the value of t_user.userEmail
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userEmail
     *
     * @param useremail the value for t_user.userEmail
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userHobby
     *
     * @return the value of t_user.userHobby
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getUserhobby() {
        return userhobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userHobby
     *
     * @param userhobby the value for t_user.userHobby
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUserhobby(String userhobby) {
        this.userhobby = userhobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userSignature
     *
     * @return the value of t_user.userSignature
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getUsersignature() {
        return usersignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userSignature
     *
     * @param usersignature the value for t_user.userSignature
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUsersignature(String usersignature) {
        this.usersignature = usersignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.headPortrait
     *
     * @return the value of t_user.headPortrait
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getHeadportrait() {
        return headportrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.headPortrait
     *
     * @param headportrait the value for t_user.headPortrait
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setHeadportrait(String headportrait) {
        this.headportrait = headportrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.modifyAllTime
     *
     * @return the value of t_user.modifyAllTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Date getModifyalltime() {
        return modifyalltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.modifyAllTime
     *
     * @param modifyalltime the value for t_user.modifyAllTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setModifyalltime(Date modifyalltime) {
        this.modifyalltime = modifyalltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.modifyAllPerson
     *
     * @return the value of t_user.modifyAllPerson
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getModifyallperson() {
        return modifyallperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.modifyAllPerson
     *
     * @param modifyallperson the value for t_user.modifyAllPerson
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setModifyallperson(String modifyallperson) {
        this.modifyallperson = modifyallperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userAge
     *
     * @return the value of t_user.userAge
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Integer getUserage() {
        return userage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userAge
     *
     * @param userage the value for t_user.userAge
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUserage(Integer userage) {
        this.userage = userage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userScore
     *
     * @return the value of t_user.userScore
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Integer getUserscore() {
        return userscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userScore
     *
     * @param userscore the value for t_user.userScore
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUserscore(Integer userscore) {
        this.userscore = userscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.Attribute1
     *
     * @return the value of t_user.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.Attribute1
     *
     * @param attribute1 the value for t_user.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.Attribute2
     *
     * @return the value of t_user.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.Attribute2
     *
     * @param attribute2 the value for t_user.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.Attribute3
     *
     * @return the value of t_user.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.Attribute3
     *
     * @param attribute3 the value for t_user.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.Attribute4
     *
     * @return the value of t_user.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.Attribute4
     *
     * @param attribute4 the value for t_user.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.Attribute5
     *
     * @return the value of t_user.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.Attribute5
     *
     * @param attribute5 the value for t_user.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.Attribute6
     *
     * @return the value of t_user.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.Attribute6
     *
     * @param attribute6 the value for t_user.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.Attribute7
     *
     * @return the value of t_user.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.Attribute7
     *
     * @param attribute7 the value for t_user.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.Attribute8
     *
     * @return the value of t_user.Attribute8
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute8() {
        return attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.Attribute8
     *
     * @param attribute8 the value for t_user.Attribute8
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }
}