package com.player.model;

import java.util.Date;

public class VCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.collecttionId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String collecttionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.videoId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String videoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.collectTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Date collecttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute7;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.collecttionId
     *
     * @return the value of t_collection.collecttionId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getCollecttionid() {
        return collecttionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.collecttionId
     *
     * @param collecttionid the value for t_collection.collecttionId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setCollecttionid(String collecttionid) {
        this.collecttionid = collecttionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.userId
     *
     * @return the value of t_collection.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.userId
     *
     * @param userid the value for t_collection.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.videoId
     *
     * @return the value of t_collection.videoId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getVideoid() {
        return videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.videoId
     *
     * @param videoid the value for t_collection.videoId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideoid(String videoid) {
        this.videoid = videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.collectTime
     *
     * @return the value of t_collection.collectTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Date getCollecttime() {
        return collecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.collectTime
     *
     * @param collecttime the value for t_collection.collectTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setCollecttime(Date collecttime) {
        this.collecttime = collecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.Attribute1
     *
     * @return the value of t_collection.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.Attribute1
     *
     * @param attribute1 the value for t_collection.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.Attribute2
     *
     * @return the value of t_collection.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.Attribute2
     *
     * @param attribute2 the value for t_collection.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.Attribute3
     *
     * @return the value of t_collection.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.Attribute3
     *
     * @param attribute3 the value for t_collection.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.Attribute4
     *
     * @return the value of t_collection.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.Attribute4
     *
     * @param attribute4 the value for t_collection.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.Attribute5
     *
     * @return the value of t_collection.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.Attribute5
     *
     * @param attribute5 the value for t_collection.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.Attribute6
     *
     * @return the value of t_collection.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.Attribute6
     *
     * @param attribute6 the value for t_collection.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.Attribute7
     *
     * @return the value of t_collection.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.Attribute7
     *
     * @param attribute7 the value for t_collection.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }
}