package com.player.model;

import java.util.Date;

public class Video {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.videoId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String videoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.videoType
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String videotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.videoScore
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Integer videoscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.videoSum
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Integer videosum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.videoCountry
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String videocountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.videoLanguage
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String videolanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.videoName
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String videoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.videoYear
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String videoyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.videoDescribe
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String videodescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.videoUploadTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private Date videouploadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.videoDirector
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String videodirector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.videoActor
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String videoactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.Attribute8
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.Attribute9
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.Attribute10
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    private String attribute10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.videoId
     *
     * @return the value of t_video.videoId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getVideoid() {
        return videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.videoId
     *
     * @param videoid the value for t_video.videoId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideoid(String videoid) {
        this.videoid = videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.videoType
     *
     * @return the value of t_video.videoType
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getVideotype() {
        return videotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.videoType
     *
     * @param videotype the value for t_video.videoType
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideotype(String videotype) {
        this.videotype = videotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.videoScore
     *
     * @return the value of t_video.videoScore
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Integer getVideoscore() {
        return videoscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.videoScore
     *
     * @param videoscore the value for t_video.videoScore
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideoscore(Integer videoscore) {
        this.videoscore = videoscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.userId
     *
     * @return the value of t_video.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.userId
     *
     * @param userid the value for t_video.userId
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.videoSum
     *
     * @return the value of t_video.videoSum
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Integer getVideosum() {
        return videosum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.videoSum
     *
     * @param videosum the value for t_video.videoSum
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideosum(Integer videosum) {
        this.videosum = videosum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.videoCountry
     *
     * @return the value of t_video.videoCountry
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getVideocountry() {
        return videocountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.videoCountry
     *
     * @param videocountry the value for t_video.videoCountry
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideocountry(String videocountry) {
        this.videocountry = videocountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.videoLanguage
     *
     * @return the value of t_video.videoLanguage
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getVideolanguage() {
        return videolanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.videoLanguage
     *
     * @param videolanguage the value for t_video.videoLanguage
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideolanguage(String videolanguage) {
        this.videolanguage = videolanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.videoName
     *
     * @return the value of t_video.videoName
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getVideoname() {
        return videoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.videoName
     *
     * @param videoname the value for t_video.videoName
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideoname(String videoname) {
        this.videoname = videoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.videoYear
     *
     * @return the value of t_video.videoYear
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getVideoyear() {
        return videoyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.videoYear
     *
     * @param videoyear the value for t_video.videoYear
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideoyear(String videoyear) {
        this.videoyear = videoyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.videoDescribe
     *
     * @return the value of t_video.videoDescribe
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getVideodescribe() {
        return videodescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.videoDescribe
     *
     * @param videodescribe the value for t_video.videoDescribe
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideodescribe(String videodescribe) {
        this.videodescribe = videodescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.videoUploadTime
     *
     * @return the value of t_video.videoUploadTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Date getVideouploadtime() {
        return videouploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.videoUploadTime
     *
     * @param videouploadtime the value for t_video.videoUploadTime
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideouploadtime(Date videouploadtime) {
        this.videouploadtime = videouploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.videoDirector
     *
     * @return the value of t_video.videoDirector
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getVideodirector() {
        return videodirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.videoDirector
     *
     * @param videodirector the value for t_video.videoDirector
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideodirector(String videodirector) {
        this.videodirector = videodirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.videoActor
     *
     * @return the value of t_video.videoActor
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getVideoactor() {
        return videoactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.videoActor
     *
     * @param videoactor the value for t_video.videoActor
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setVideoactor(String videoactor) {
        this.videoactor = videoactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.Attribute1
     *
     * @return the value of t_video.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.Attribute1
     *
     * @param attribute1 the value for t_video.Attribute1
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.Attribute2
     *
     * @return the value of t_video.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.Attribute2
     *
     * @param attribute2 the value for t_video.Attribute2
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.Attribute3
     *
     * @return the value of t_video.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.Attribute3
     *
     * @param attribute3 the value for t_video.Attribute3
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.Attribute4
     *
     * @return the value of t_video.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.Attribute4
     *
     * @param attribute4 the value for t_video.Attribute4
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.Attribute5
     *
     * @return the value of t_video.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.Attribute5
     *
     * @param attribute5 the value for t_video.Attribute5
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.Attribute6
     *
     * @return the value of t_video.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.Attribute6
     *
     * @param attribute6 the value for t_video.Attribute6
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.Attribute7
     *
     * @return the value of t_video.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.Attribute7
     *
     * @param attribute7 the value for t_video.Attribute7
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.Attribute8
     *
     * @return the value of t_video.Attribute8
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute8() {
        return attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.Attribute8
     *
     * @param attribute8 the value for t_video.Attribute8
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.Attribute9
     *
     * @return the value of t_video.Attribute9
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute9() {
        return attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.Attribute9
     *
     * @param attribute9 the value for t_video.Attribute9
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute9(String attribute9) {
        this.attribute9 = attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.Attribute10
     *
     * @return the value of t_video.Attribute10
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getAttribute10() {
        return attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.Attribute10
     *
     * @param attribute10 the value for t_video.Attribute10
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setAttribute10(String attribute10) {
        this.attribute10 = attribute10;
    }
}