package com.player.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VideoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public VideoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVideoidIsNull() {
            addCriterion("videoId is null");
            return (Criteria) this;
        }

        public Criteria andVideoidIsNotNull() {
            addCriterion("videoId is not null");
            return (Criteria) this;
        }

        public Criteria andVideoidEqualTo(String value) {
            addCriterion("videoId =", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidNotEqualTo(String value) {
            addCriterion("videoId <>", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidGreaterThan(String value) {
            addCriterion("videoId >", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidGreaterThanOrEqualTo(String value) {
            addCriterion("videoId >=", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidLessThan(String value) {
            addCriterion("videoId <", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidLessThanOrEqualTo(String value) {
            addCriterion("videoId <=", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidLike(String value) {
            addCriterion("videoId like", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidNotLike(String value) {
            addCriterion("videoId not like", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidIn(List<String> values) {
            addCriterion("videoId in", values, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidNotIn(List<String> values) {
            addCriterion("videoId not in", values, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidBetween(String value1, String value2) {
            addCriterion("videoId between", value1, value2, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidNotBetween(String value1, String value2) {
            addCriterion("videoId not between", value1, value2, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideotypeIsNull() {
            addCriterion("videoType is null");
            return (Criteria) this;
        }

        public Criteria andVideotypeIsNotNull() {
            addCriterion("videoType is not null");
            return (Criteria) this;
        }

        public Criteria andVideotypeEqualTo(String value) {
            addCriterion("videoType =", value, "videotype");
            return (Criteria) this;
        }

        public Criteria andVideotypeNotEqualTo(String value) {
            addCriterion("videoType <>", value, "videotype");
            return (Criteria) this;
        }

        public Criteria andVideotypeGreaterThan(String value) {
            addCriterion("videoType >", value, "videotype");
            return (Criteria) this;
        }

        public Criteria andVideotypeGreaterThanOrEqualTo(String value) {
            addCriterion("videoType >=", value, "videotype");
            return (Criteria) this;
        }

        public Criteria andVideotypeLessThan(String value) {
            addCriterion("videoType <", value, "videotype");
            return (Criteria) this;
        }

        public Criteria andVideotypeLessThanOrEqualTo(String value) {
            addCriterion("videoType <=", value, "videotype");
            return (Criteria) this;
        }

        public Criteria andVideotypeLike(String value) {
            addCriterion("videoType like", value, "videotype");
            return (Criteria) this;
        }

        public Criteria andVideotypeNotLike(String value) {
            addCriterion("videoType not like", value, "videotype");
            return (Criteria) this;
        }

        public Criteria andVideotypeIn(List<String> values) {
            addCriterion("videoType in", values, "videotype");
            return (Criteria) this;
        }

        public Criteria andVideotypeNotIn(List<String> values) {
            addCriterion("videoType not in", values, "videotype");
            return (Criteria) this;
        }

        public Criteria andVideotypeBetween(String value1, String value2) {
            addCriterion("videoType between", value1, value2, "videotype");
            return (Criteria) this;
        }

        public Criteria andVideotypeNotBetween(String value1, String value2) {
            addCriterion("videoType not between", value1, value2, "videotype");
            return (Criteria) this;
        }

        public Criteria andVideoscoreIsNull() {
            addCriterion("videoScore is null");
            return (Criteria) this;
        }

        public Criteria andVideoscoreIsNotNull() {
            addCriterion("videoScore is not null");
            return (Criteria) this;
        }

        public Criteria andVideoscoreEqualTo(Integer value) {
            addCriterion("videoScore =", value, "videoscore");
            return (Criteria) this;
        }

        public Criteria andVideoscoreNotEqualTo(Integer value) {
            addCriterion("videoScore <>", value, "videoscore");
            return (Criteria) this;
        }

        public Criteria andVideoscoreGreaterThan(Integer value) {
            addCriterion("videoScore >", value, "videoscore");
            return (Criteria) this;
        }

        public Criteria andVideoscoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("videoScore >=", value, "videoscore");
            return (Criteria) this;
        }

        public Criteria andVideoscoreLessThan(Integer value) {
            addCriterion("videoScore <", value, "videoscore");
            return (Criteria) this;
        }

        public Criteria andVideoscoreLessThanOrEqualTo(Integer value) {
            addCriterion("videoScore <=", value, "videoscore");
            return (Criteria) this;
        }

        public Criteria andVideoscoreIn(List<Integer> values) {
            addCriterion("videoScore in", values, "videoscore");
            return (Criteria) this;
        }

        public Criteria andVideoscoreNotIn(List<Integer> values) {
            addCriterion("videoScore not in", values, "videoscore");
            return (Criteria) this;
        }

        public Criteria andVideoscoreBetween(Integer value1, Integer value2) {
            addCriterion("videoScore between", value1, value2, "videoscore");
            return (Criteria) this;
        }

        public Criteria andVideoscoreNotBetween(Integer value1, Integer value2) {
            addCriterion("videoScore not between", value1, value2, "videoscore");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("userId like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("userId not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andVideosumIsNull() {
            addCriterion("videoSum is null");
            return (Criteria) this;
        }

        public Criteria andVideosumIsNotNull() {
            addCriterion("videoSum is not null");
            return (Criteria) this;
        }

        public Criteria andVideosumEqualTo(Integer value) {
            addCriterion("videoSum =", value, "videosum");
            return (Criteria) this;
        }

        public Criteria andVideosumNotEqualTo(Integer value) {
            addCriterion("videoSum <>", value, "videosum");
            return (Criteria) this;
        }

        public Criteria andVideosumGreaterThan(Integer value) {
            addCriterion("videoSum >", value, "videosum");
            return (Criteria) this;
        }

        public Criteria andVideosumGreaterThanOrEqualTo(Integer value) {
            addCriterion("videoSum >=", value, "videosum");
            return (Criteria) this;
        }

        public Criteria andVideosumLessThan(Integer value) {
            addCriterion("videoSum <", value, "videosum");
            return (Criteria) this;
        }

        public Criteria andVideosumLessThanOrEqualTo(Integer value) {
            addCriterion("videoSum <=", value, "videosum");
            return (Criteria) this;
        }

        public Criteria andVideosumIn(List<Integer> values) {
            addCriterion("videoSum in", values, "videosum");
            return (Criteria) this;
        }

        public Criteria andVideosumNotIn(List<Integer> values) {
            addCriterion("videoSum not in", values, "videosum");
            return (Criteria) this;
        }

        public Criteria andVideosumBetween(Integer value1, Integer value2) {
            addCriterion("videoSum between", value1, value2, "videosum");
            return (Criteria) this;
        }

        public Criteria andVideosumNotBetween(Integer value1, Integer value2) {
            addCriterion("videoSum not between", value1, value2, "videosum");
            return (Criteria) this;
        }

        public Criteria andVideocountryIsNull() {
            addCriterion("videoCountry is null");
            return (Criteria) this;
        }

        public Criteria andVideocountryIsNotNull() {
            addCriterion("videoCountry is not null");
            return (Criteria) this;
        }

        public Criteria andVideocountryEqualTo(String value) {
            addCriterion("videoCountry =", value, "videocountry");
            return (Criteria) this;
        }

        public Criteria andVideocountryNotEqualTo(String value) {
            addCriterion("videoCountry <>", value, "videocountry");
            return (Criteria) this;
        }

        public Criteria andVideocountryGreaterThan(String value) {
            addCriterion("videoCountry >", value, "videocountry");
            return (Criteria) this;
        }

        public Criteria andVideocountryGreaterThanOrEqualTo(String value) {
            addCriterion("videoCountry >=", value, "videocountry");
            return (Criteria) this;
        }

        public Criteria andVideocountryLessThan(String value) {
            addCriterion("videoCountry <", value, "videocountry");
            return (Criteria) this;
        }

        public Criteria andVideocountryLessThanOrEqualTo(String value) {
            addCriterion("videoCountry <=", value, "videocountry");
            return (Criteria) this;
        }

        public Criteria andVideocountryLike(String value) {
            addCriterion("videoCountry like", value, "videocountry");
            return (Criteria) this;
        }

        public Criteria andVideocountryNotLike(String value) {
            addCriterion("videoCountry not like", value, "videocountry");
            return (Criteria) this;
        }

        public Criteria andVideocountryIn(List<String> values) {
            addCriterion("videoCountry in", values, "videocountry");
            return (Criteria) this;
        }

        public Criteria andVideocountryNotIn(List<String> values) {
            addCriterion("videoCountry not in", values, "videocountry");
            return (Criteria) this;
        }

        public Criteria andVideocountryBetween(String value1, String value2) {
            addCriterion("videoCountry between", value1, value2, "videocountry");
            return (Criteria) this;
        }

        public Criteria andVideocountryNotBetween(String value1, String value2) {
            addCriterion("videoCountry not between", value1, value2, "videocountry");
            return (Criteria) this;
        }

        public Criteria andVideolanguageIsNull() {
            addCriterion("videoLanguage is null");
            return (Criteria) this;
        }

        public Criteria andVideolanguageIsNotNull() {
            addCriterion("videoLanguage is not null");
            return (Criteria) this;
        }

        public Criteria andVideolanguageEqualTo(String value) {
            addCriterion("videoLanguage =", value, "videolanguage");
            return (Criteria) this;
        }

        public Criteria andVideolanguageNotEqualTo(String value) {
            addCriterion("videoLanguage <>", value, "videolanguage");
            return (Criteria) this;
        }

        public Criteria andVideolanguageGreaterThan(String value) {
            addCriterion("videoLanguage >", value, "videolanguage");
            return (Criteria) this;
        }

        public Criteria andVideolanguageGreaterThanOrEqualTo(String value) {
            addCriterion("videoLanguage >=", value, "videolanguage");
            return (Criteria) this;
        }

        public Criteria andVideolanguageLessThan(String value) {
            addCriterion("videoLanguage <", value, "videolanguage");
            return (Criteria) this;
        }

        public Criteria andVideolanguageLessThanOrEqualTo(String value) {
            addCriterion("videoLanguage <=", value, "videolanguage");
            return (Criteria) this;
        }

        public Criteria andVideolanguageLike(String value) {
            addCriterion("videoLanguage like", value, "videolanguage");
            return (Criteria) this;
        }

        public Criteria andVideolanguageNotLike(String value) {
            addCriterion("videoLanguage not like", value, "videolanguage");
            return (Criteria) this;
        }

        public Criteria andVideolanguageIn(List<String> values) {
            addCriterion("videoLanguage in", values, "videolanguage");
            return (Criteria) this;
        }

        public Criteria andVideolanguageNotIn(List<String> values) {
            addCriterion("videoLanguage not in", values, "videolanguage");
            return (Criteria) this;
        }

        public Criteria andVideolanguageBetween(String value1, String value2) {
            addCriterion("videoLanguage between", value1, value2, "videolanguage");
            return (Criteria) this;
        }

        public Criteria andVideolanguageNotBetween(String value1, String value2) {
            addCriterion("videoLanguage not between", value1, value2, "videolanguage");
            return (Criteria) this;
        }

        public Criteria andVideonameIsNull() {
            addCriterion("videoName is null");
            return (Criteria) this;
        }

        public Criteria andVideonameIsNotNull() {
            addCriterion("videoName is not null");
            return (Criteria) this;
        }

        public Criteria andVideonameEqualTo(String value) {
            addCriterion("videoName =", value, "videoname");
            return (Criteria) this;
        }

        public Criteria andVideonameNotEqualTo(String value) {
            addCriterion("videoName <>", value, "videoname");
            return (Criteria) this;
        }

        public Criteria andVideonameGreaterThan(String value) {
            addCriterion("videoName >", value, "videoname");
            return (Criteria) this;
        }

        public Criteria andVideonameGreaterThanOrEqualTo(String value) {
            addCriterion("videoName >=", value, "videoname");
            return (Criteria) this;
        }

        public Criteria andVideonameLessThan(String value) {
            addCriterion("videoName <", value, "videoname");
            return (Criteria) this;
        }

        public Criteria andVideonameLessThanOrEqualTo(String value) {
            addCriterion("videoName <=", value, "videoname");
            return (Criteria) this;
        }

        public Criteria andVideonameLike(String value) {
            addCriterion("videoName like", value, "videoname");
            return (Criteria) this;
        }

        public Criteria andVideonameNotLike(String value) {
            addCriterion("videoName not like", value, "videoname");
            return (Criteria) this;
        }

        public Criteria andVideonameIn(List<String> values) {
            addCriterion("videoName in", values, "videoname");
            return (Criteria) this;
        }

        public Criteria andVideonameNotIn(List<String> values) {
            addCriterion("videoName not in", values, "videoname");
            return (Criteria) this;
        }

        public Criteria andVideonameBetween(String value1, String value2) {
            addCriterion("videoName between", value1, value2, "videoname");
            return (Criteria) this;
        }

        public Criteria andVideonameNotBetween(String value1, String value2) {
            addCriterion("videoName not between", value1, value2, "videoname");
            return (Criteria) this;
        }

        public Criteria andVideoyearIsNull() {
            addCriterion("videoYear is null");
            return (Criteria) this;
        }

        public Criteria andVideoyearIsNotNull() {
            addCriterion("videoYear is not null");
            return (Criteria) this;
        }

        public Criteria andVideoyearEqualTo(String value) {
            addCriterion("videoYear =", value, "videoyear");
            return (Criteria) this;
        }

        public Criteria andVideoyearNotEqualTo(String value) {
            addCriterion("videoYear <>", value, "videoyear");
            return (Criteria) this;
        }

        public Criteria andVideoyearGreaterThan(String value) {
            addCriterion("videoYear >", value, "videoyear");
            return (Criteria) this;
        }

        public Criteria andVideoyearGreaterThanOrEqualTo(String value) {
            addCriterion("videoYear >=", value, "videoyear");
            return (Criteria) this;
        }

        public Criteria andVideoyearLessThan(String value) {
            addCriterion("videoYear <", value, "videoyear");
            return (Criteria) this;
        }

        public Criteria andVideoyearLessThanOrEqualTo(String value) {
            addCriterion("videoYear <=", value, "videoyear");
            return (Criteria) this;
        }

        public Criteria andVideoyearLike(String value) {
            addCriterion("videoYear like", value, "videoyear");
            return (Criteria) this;
        }

        public Criteria andVideoyearNotLike(String value) {
            addCriterion("videoYear not like", value, "videoyear");
            return (Criteria) this;
        }

        public Criteria andVideoyearIn(List<String> values) {
            addCriterion("videoYear in", values, "videoyear");
            return (Criteria) this;
        }

        public Criteria andVideoyearNotIn(List<String> values) {
            addCriterion("videoYear not in", values, "videoyear");
            return (Criteria) this;
        }

        public Criteria andVideoyearBetween(String value1, String value2) {
            addCriterion("videoYear between", value1, value2, "videoyear");
            return (Criteria) this;
        }

        public Criteria andVideoyearNotBetween(String value1, String value2) {
            addCriterion("videoYear not between", value1, value2, "videoyear");
            return (Criteria) this;
        }

        public Criteria andVideodescribeIsNull() {
            addCriterion("videoDescribe is null");
            return (Criteria) this;
        }

        public Criteria andVideodescribeIsNotNull() {
            addCriterion("videoDescribe is not null");
            return (Criteria) this;
        }

        public Criteria andVideodescribeEqualTo(String value) {
            addCriterion("videoDescribe =", value, "videodescribe");
            return (Criteria) this;
        }

        public Criteria andVideodescribeNotEqualTo(String value) {
            addCriterion("videoDescribe <>", value, "videodescribe");
            return (Criteria) this;
        }

        public Criteria andVideodescribeGreaterThan(String value) {
            addCriterion("videoDescribe >", value, "videodescribe");
            return (Criteria) this;
        }

        public Criteria andVideodescribeGreaterThanOrEqualTo(String value) {
            addCriterion("videoDescribe >=", value, "videodescribe");
            return (Criteria) this;
        }

        public Criteria andVideodescribeLessThan(String value) {
            addCriterion("videoDescribe <", value, "videodescribe");
            return (Criteria) this;
        }

        public Criteria andVideodescribeLessThanOrEqualTo(String value) {
            addCriterion("videoDescribe <=", value, "videodescribe");
            return (Criteria) this;
        }

        public Criteria andVideodescribeLike(String value) {
            addCriterion("videoDescribe like", value, "videodescribe");
            return (Criteria) this;
        }

        public Criteria andVideodescribeNotLike(String value) {
            addCriterion("videoDescribe not like", value, "videodescribe");
            return (Criteria) this;
        }

        public Criteria andVideodescribeIn(List<String> values) {
            addCriterion("videoDescribe in", values, "videodescribe");
            return (Criteria) this;
        }

        public Criteria andVideodescribeNotIn(List<String> values) {
            addCriterion("videoDescribe not in", values, "videodescribe");
            return (Criteria) this;
        }

        public Criteria andVideodescribeBetween(String value1, String value2) {
            addCriterion("videoDescribe between", value1, value2, "videodescribe");
            return (Criteria) this;
        }

        public Criteria andVideodescribeNotBetween(String value1, String value2) {
            addCriterion("videoDescribe not between", value1, value2, "videodescribe");
            return (Criteria) this;
        }

        public Criteria andVideouploadtimeIsNull() {
            addCriterion("videoUploadTime is null");
            return (Criteria) this;
        }

        public Criteria andVideouploadtimeIsNotNull() {
            addCriterion("videoUploadTime is not null");
            return (Criteria) this;
        }

        public Criteria andVideouploadtimeEqualTo(Date value) {
            addCriterion("videoUploadTime =", value, "videouploadtime");
            return (Criteria) this;
        }

        public Criteria andVideouploadtimeNotEqualTo(Date value) {
            addCriterion("videoUploadTime <>", value, "videouploadtime");
            return (Criteria) this;
        }

        public Criteria andVideouploadtimeGreaterThan(Date value) {
            addCriterion("videoUploadTime >", value, "videouploadtime");
            return (Criteria) this;
        }

        public Criteria andVideouploadtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("videoUploadTime >=", value, "videouploadtime");
            return (Criteria) this;
        }

        public Criteria andVideouploadtimeLessThan(Date value) {
            addCriterion("videoUploadTime <", value, "videouploadtime");
            return (Criteria) this;
        }

        public Criteria andVideouploadtimeLessThanOrEqualTo(Date value) {
            addCriterion("videoUploadTime <=", value, "videouploadtime");
            return (Criteria) this;
        }

        public Criteria andVideouploadtimeIn(List<Date> values) {
            addCriterion("videoUploadTime in", values, "videouploadtime");
            return (Criteria) this;
        }

        public Criteria andVideouploadtimeNotIn(List<Date> values) {
            addCriterion("videoUploadTime not in", values, "videouploadtime");
            return (Criteria) this;
        }

        public Criteria andVideouploadtimeBetween(Date value1, Date value2) {
            addCriterion("videoUploadTime between", value1, value2, "videouploadtime");
            return (Criteria) this;
        }

        public Criteria andVideouploadtimeNotBetween(Date value1, Date value2) {
            addCriterion("videoUploadTime not between", value1, value2, "videouploadtime");
            return (Criteria) this;
        }

        public Criteria andVideodirectorIsNull() {
            addCriterion("videoDirector is null");
            return (Criteria) this;
        }

        public Criteria andVideodirectorIsNotNull() {
            addCriterion("videoDirector is not null");
            return (Criteria) this;
        }

        public Criteria andVideodirectorEqualTo(String value) {
            addCriterion("videoDirector =", value, "videodirector");
            return (Criteria) this;
        }

        public Criteria andVideodirectorNotEqualTo(String value) {
            addCriterion("videoDirector <>", value, "videodirector");
            return (Criteria) this;
        }

        public Criteria andVideodirectorGreaterThan(String value) {
            addCriterion("videoDirector >", value, "videodirector");
            return (Criteria) this;
        }

        public Criteria andVideodirectorGreaterThanOrEqualTo(String value) {
            addCriterion("videoDirector >=", value, "videodirector");
            return (Criteria) this;
        }

        public Criteria andVideodirectorLessThan(String value) {
            addCriterion("videoDirector <", value, "videodirector");
            return (Criteria) this;
        }

        public Criteria andVideodirectorLessThanOrEqualTo(String value) {
            addCriterion("videoDirector <=", value, "videodirector");
            return (Criteria) this;
        }

        public Criteria andVideodirectorLike(String value) {
            addCriterion("videoDirector like", value, "videodirector");
            return (Criteria) this;
        }

        public Criteria andVideodirectorNotLike(String value) {
            addCriterion("videoDirector not like", value, "videodirector");
            return (Criteria) this;
        }

        public Criteria andVideodirectorIn(List<String> values) {
            addCriterion("videoDirector in", values, "videodirector");
            return (Criteria) this;
        }

        public Criteria andVideodirectorNotIn(List<String> values) {
            addCriterion("videoDirector not in", values, "videodirector");
            return (Criteria) this;
        }

        public Criteria andVideodirectorBetween(String value1, String value2) {
            addCriterion("videoDirector between", value1, value2, "videodirector");
            return (Criteria) this;
        }

        public Criteria andVideodirectorNotBetween(String value1, String value2) {
            addCriterion("videoDirector not between", value1, value2, "videodirector");
            return (Criteria) this;
        }

        public Criteria andVideoactorIsNull() {
            addCriterion("videoActor is null");
            return (Criteria) this;
        }

        public Criteria andVideoactorIsNotNull() {
            addCriterion("videoActor is not null");
            return (Criteria) this;
        }

        public Criteria andVideoactorEqualTo(String value) {
            addCriterion("videoActor =", value, "videoactor");
            return (Criteria) this;
        }

        public Criteria andVideoactorNotEqualTo(String value) {
            addCriterion("videoActor <>", value, "videoactor");
            return (Criteria) this;
        }

        public Criteria andVideoactorGreaterThan(String value) {
            addCriterion("videoActor >", value, "videoactor");
            return (Criteria) this;
        }

        public Criteria andVideoactorGreaterThanOrEqualTo(String value) {
            addCriterion("videoActor >=", value, "videoactor");
            return (Criteria) this;
        }

        public Criteria andVideoactorLessThan(String value) {
            addCriterion("videoActor <", value, "videoactor");
            return (Criteria) this;
        }

        public Criteria andVideoactorLessThanOrEqualTo(String value) {
            addCriterion("videoActor <=", value, "videoactor");
            return (Criteria) this;
        }

        public Criteria andVideoactorLike(String value) {
            addCriterion("videoActor like", value, "videoactor");
            return (Criteria) this;
        }

        public Criteria andVideoactorNotLike(String value) {
            addCriterion("videoActor not like", value, "videoactor");
            return (Criteria) this;
        }

        public Criteria andVideoactorIn(List<String> values) {
            addCriterion("videoActor in", values, "videoactor");
            return (Criteria) this;
        }

        public Criteria andVideoactorNotIn(List<String> values) {
            addCriterion("videoActor not in", values, "videoactor");
            return (Criteria) this;
        }

        public Criteria andVideoactorBetween(String value1, String value2) {
            addCriterion("videoActor between", value1, value2, "videoactor");
            return (Criteria) this;
        }

        public Criteria andVideoactorNotBetween(String value1, String value2) {
            addCriterion("videoActor not between", value1, value2, "videoactor");
            return (Criteria) this;
        }

        public Criteria andAttribute1IsNull() {
            addCriterion("Attribute1 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute1IsNotNull() {
            addCriterion("Attribute1 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute1EqualTo(String value) {
            addCriterion("Attribute1 =", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotEqualTo(String value) {
            addCriterion("Attribute1 <>", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1GreaterThan(String value) {
            addCriterion("Attribute1 >", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1GreaterThanOrEqualTo(String value) {
            addCriterion("Attribute1 >=", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1LessThan(String value) {
            addCriterion("Attribute1 <", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1LessThanOrEqualTo(String value) {
            addCriterion("Attribute1 <=", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1Like(String value) {
            addCriterion("Attribute1 like", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotLike(String value) {
            addCriterion("Attribute1 not like", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1In(List<String> values) {
            addCriterion("Attribute1 in", values, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotIn(List<String> values) {
            addCriterion("Attribute1 not in", values, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1Between(String value1, String value2) {
            addCriterion("Attribute1 between", value1, value2, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotBetween(String value1, String value2) {
            addCriterion("Attribute1 not between", value1, value2, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute2IsNull() {
            addCriterion("Attribute2 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute2IsNotNull() {
            addCriterion("Attribute2 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute2EqualTo(String value) {
            addCriterion("Attribute2 =", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotEqualTo(String value) {
            addCriterion("Attribute2 <>", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2GreaterThan(String value) {
            addCriterion("Attribute2 >", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2GreaterThanOrEqualTo(String value) {
            addCriterion("Attribute2 >=", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2LessThan(String value) {
            addCriterion("Attribute2 <", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2LessThanOrEqualTo(String value) {
            addCriterion("Attribute2 <=", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2Like(String value) {
            addCriterion("Attribute2 like", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotLike(String value) {
            addCriterion("Attribute2 not like", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2In(List<String> values) {
            addCriterion("Attribute2 in", values, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotIn(List<String> values) {
            addCriterion("Attribute2 not in", values, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2Between(String value1, String value2) {
            addCriterion("Attribute2 between", value1, value2, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotBetween(String value1, String value2) {
            addCriterion("Attribute2 not between", value1, value2, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute3IsNull() {
            addCriterion("Attribute3 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute3IsNotNull() {
            addCriterion("Attribute3 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute3EqualTo(String value) {
            addCriterion("Attribute3 =", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotEqualTo(String value) {
            addCriterion("Attribute3 <>", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3GreaterThan(String value) {
            addCriterion("Attribute3 >", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3GreaterThanOrEqualTo(String value) {
            addCriterion("Attribute3 >=", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3LessThan(String value) {
            addCriterion("Attribute3 <", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3LessThanOrEqualTo(String value) {
            addCriterion("Attribute3 <=", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3Like(String value) {
            addCriterion("Attribute3 like", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotLike(String value) {
            addCriterion("Attribute3 not like", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3In(List<String> values) {
            addCriterion("Attribute3 in", values, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotIn(List<String> values) {
            addCriterion("Attribute3 not in", values, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3Between(String value1, String value2) {
            addCriterion("Attribute3 between", value1, value2, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotBetween(String value1, String value2) {
            addCriterion("Attribute3 not between", value1, value2, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute4IsNull() {
            addCriterion("Attribute4 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute4IsNotNull() {
            addCriterion("Attribute4 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute4EqualTo(String value) {
            addCriterion("Attribute4 =", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotEqualTo(String value) {
            addCriterion("Attribute4 <>", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4GreaterThan(String value) {
            addCriterion("Attribute4 >", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4GreaterThanOrEqualTo(String value) {
            addCriterion("Attribute4 >=", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4LessThan(String value) {
            addCriterion("Attribute4 <", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4LessThanOrEqualTo(String value) {
            addCriterion("Attribute4 <=", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4Like(String value) {
            addCriterion("Attribute4 like", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotLike(String value) {
            addCriterion("Attribute4 not like", value, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4In(List<String> values) {
            addCriterion("Attribute4 in", values, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotIn(List<String> values) {
            addCriterion("Attribute4 not in", values, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4Between(String value1, String value2) {
            addCriterion("Attribute4 between", value1, value2, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute4NotBetween(String value1, String value2) {
            addCriterion("Attribute4 not between", value1, value2, "attribute4");
            return (Criteria) this;
        }

        public Criteria andAttribute5IsNull() {
            addCriterion("Attribute5 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute5IsNotNull() {
            addCriterion("Attribute5 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute5EqualTo(String value) {
            addCriterion("Attribute5 =", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotEqualTo(String value) {
            addCriterion("Attribute5 <>", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5GreaterThan(String value) {
            addCriterion("Attribute5 >", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5GreaterThanOrEqualTo(String value) {
            addCriterion("Attribute5 >=", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5LessThan(String value) {
            addCriterion("Attribute5 <", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5LessThanOrEqualTo(String value) {
            addCriterion("Attribute5 <=", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5Like(String value) {
            addCriterion("Attribute5 like", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotLike(String value) {
            addCriterion("Attribute5 not like", value, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5In(List<String> values) {
            addCriterion("Attribute5 in", values, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotIn(List<String> values) {
            addCriterion("Attribute5 not in", values, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5Between(String value1, String value2) {
            addCriterion("Attribute5 between", value1, value2, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute5NotBetween(String value1, String value2) {
            addCriterion("Attribute5 not between", value1, value2, "attribute5");
            return (Criteria) this;
        }

        public Criteria andAttribute6IsNull() {
            addCriterion("Attribute6 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute6IsNotNull() {
            addCriterion("Attribute6 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute6EqualTo(String value) {
            addCriterion("Attribute6 =", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6NotEqualTo(String value) {
            addCriterion("Attribute6 <>", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6GreaterThan(String value) {
            addCriterion("Attribute6 >", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6GreaterThanOrEqualTo(String value) {
            addCriterion("Attribute6 >=", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6LessThan(String value) {
            addCriterion("Attribute6 <", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6LessThanOrEqualTo(String value) {
            addCriterion("Attribute6 <=", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6Like(String value) {
            addCriterion("Attribute6 like", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6NotLike(String value) {
            addCriterion("Attribute6 not like", value, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6In(List<String> values) {
            addCriterion("Attribute6 in", values, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6NotIn(List<String> values) {
            addCriterion("Attribute6 not in", values, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6Between(String value1, String value2) {
            addCriterion("Attribute6 between", value1, value2, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute6NotBetween(String value1, String value2) {
            addCriterion("Attribute6 not between", value1, value2, "attribute6");
            return (Criteria) this;
        }

        public Criteria andAttribute7IsNull() {
            addCriterion("Attribute7 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute7IsNotNull() {
            addCriterion("Attribute7 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute7EqualTo(String value) {
            addCriterion("Attribute7 =", value, "attribute7");
            return (Criteria) this;
        }

        public Criteria andAttribute7NotEqualTo(String value) {
            addCriterion("Attribute7 <>", value, "attribute7");
            return (Criteria) this;
        }

        public Criteria andAttribute7GreaterThan(String value) {
            addCriterion("Attribute7 >", value, "attribute7");
            return (Criteria) this;
        }

        public Criteria andAttribute7GreaterThanOrEqualTo(String value) {
            addCriterion("Attribute7 >=", value, "attribute7");
            return (Criteria) this;
        }

        public Criteria andAttribute7LessThan(String value) {
            addCriterion("Attribute7 <", value, "attribute7");
            return (Criteria) this;
        }

        public Criteria andAttribute7LessThanOrEqualTo(String value) {
            addCriterion("Attribute7 <=", value, "attribute7");
            return (Criteria) this;
        }

        public Criteria andAttribute7Like(String value) {
            addCriterion("Attribute7 like", value, "attribute7");
            return (Criteria) this;
        }

        public Criteria andAttribute7NotLike(String value) {
            addCriterion("Attribute7 not like", value, "attribute7");
            return (Criteria) this;
        }

        public Criteria andAttribute7In(List<String> values) {
            addCriterion("Attribute7 in", values, "attribute7");
            return (Criteria) this;
        }

        public Criteria andAttribute7NotIn(List<String> values) {
            addCriterion("Attribute7 not in", values, "attribute7");
            return (Criteria) this;
        }

        public Criteria andAttribute7Between(String value1, String value2) {
            addCriterion("Attribute7 between", value1, value2, "attribute7");
            return (Criteria) this;
        }

        public Criteria andAttribute7NotBetween(String value1, String value2) {
            addCriterion("Attribute7 not between", value1, value2, "attribute7");
            return (Criteria) this;
        }

        public Criteria andAttribute8IsNull() {
            addCriterion("Attribute8 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute8IsNotNull() {
            addCriterion("Attribute8 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute8EqualTo(String value) {
            addCriterion("Attribute8 =", value, "attribute8");
            return (Criteria) this;
        }

        public Criteria andAttribute8NotEqualTo(String value) {
            addCriterion("Attribute8 <>", value, "attribute8");
            return (Criteria) this;
        }

        public Criteria andAttribute8GreaterThan(String value) {
            addCriterion("Attribute8 >", value, "attribute8");
            return (Criteria) this;
        }

        public Criteria andAttribute8GreaterThanOrEqualTo(String value) {
            addCriterion("Attribute8 >=", value, "attribute8");
            return (Criteria) this;
        }

        public Criteria andAttribute8LessThan(String value) {
            addCriterion("Attribute8 <", value, "attribute8");
            return (Criteria) this;
        }

        public Criteria andAttribute8LessThanOrEqualTo(String value) {
            addCriterion("Attribute8 <=", value, "attribute8");
            return (Criteria) this;
        }

        public Criteria andAttribute8Like(String value) {
            addCriterion("Attribute8 like", value, "attribute8");
            return (Criteria) this;
        }

        public Criteria andAttribute8NotLike(String value) {
            addCriterion("Attribute8 not like", value, "attribute8");
            return (Criteria) this;
        }

        public Criteria andAttribute8In(List<String> values) {
            addCriterion("Attribute8 in", values, "attribute8");
            return (Criteria) this;
        }

        public Criteria andAttribute8NotIn(List<String> values) {
            addCriterion("Attribute8 not in", values, "attribute8");
            return (Criteria) this;
        }

        public Criteria andAttribute8Between(String value1, String value2) {
            addCriterion("Attribute8 between", value1, value2, "attribute8");
            return (Criteria) this;
        }

        public Criteria andAttribute8NotBetween(String value1, String value2) {
            addCriterion("Attribute8 not between", value1, value2, "attribute8");
            return (Criteria) this;
        }

        public Criteria andAttribute9IsNull() {
            addCriterion("Attribute9 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute9IsNotNull() {
            addCriterion("Attribute9 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute9EqualTo(String value) {
            addCriterion("Attribute9 =", value, "attribute9");
            return (Criteria) this;
        }

        public Criteria andAttribute9NotEqualTo(String value) {
            addCriterion("Attribute9 <>", value, "attribute9");
            return (Criteria) this;
        }

        public Criteria andAttribute9GreaterThan(String value) {
            addCriterion("Attribute9 >", value, "attribute9");
            return (Criteria) this;
        }

        public Criteria andAttribute9GreaterThanOrEqualTo(String value) {
            addCriterion("Attribute9 >=", value, "attribute9");
            return (Criteria) this;
        }

        public Criteria andAttribute9LessThan(String value) {
            addCriterion("Attribute9 <", value, "attribute9");
            return (Criteria) this;
        }

        public Criteria andAttribute9LessThanOrEqualTo(String value) {
            addCriterion("Attribute9 <=", value, "attribute9");
            return (Criteria) this;
        }

        public Criteria andAttribute9Like(String value) {
            addCriterion("Attribute9 like", value, "attribute9");
            return (Criteria) this;
        }

        public Criteria andAttribute9NotLike(String value) {
            addCriterion("Attribute9 not like", value, "attribute9");
            return (Criteria) this;
        }

        public Criteria andAttribute9In(List<String> values) {
            addCriterion("Attribute9 in", values, "attribute9");
            return (Criteria) this;
        }

        public Criteria andAttribute9NotIn(List<String> values) {
            addCriterion("Attribute9 not in", values, "attribute9");
            return (Criteria) this;
        }

        public Criteria andAttribute9Between(String value1, String value2) {
            addCriterion("Attribute9 between", value1, value2, "attribute9");
            return (Criteria) this;
        }

        public Criteria andAttribute9NotBetween(String value1, String value2) {
            addCriterion("Attribute9 not between", value1, value2, "attribute9");
            return (Criteria) this;
        }

        public Criteria andAttribute10IsNull() {
            addCriterion("Attribute10 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute10IsNotNull() {
            addCriterion("Attribute10 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute10EqualTo(String value) {
            addCriterion("Attribute10 =", value, "attribute10");
            return (Criteria) this;
        }

        public Criteria andAttribute10NotEqualTo(String value) {
            addCriterion("Attribute10 <>", value, "attribute10");
            return (Criteria) this;
        }

        public Criteria andAttribute10GreaterThan(String value) {
            addCriterion("Attribute10 >", value, "attribute10");
            return (Criteria) this;
        }

        public Criteria andAttribute10GreaterThanOrEqualTo(String value) {
            addCriterion("Attribute10 >=", value, "attribute10");
            return (Criteria) this;
        }

        public Criteria andAttribute10LessThan(String value) {
            addCriterion("Attribute10 <", value, "attribute10");
            return (Criteria) this;
        }

        public Criteria andAttribute10LessThanOrEqualTo(String value) {
            addCriterion("Attribute10 <=", value, "attribute10");
            return (Criteria) this;
        }

        public Criteria andAttribute10Like(String value) {
            addCriterion("Attribute10 like", value, "attribute10");
            return (Criteria) this;
        }

        public Criteria andAttribute10NotLike(String value) {
            addCriterion("Attribute10 not like", value, "attribute10");
            return (Criteria) this;
        }

        public Criteria andAttribute10In(List<String> values) {
            addCriterion("Attribute10 in", values, "attribute10");
            return (Criteria) this;
        }

        public Criteria andAttribute10NotIn(List<String> values) {
            addCriterion("Attribute10 not in", values, "attribute10");
            return (Criteria) this;
        }

        public Criteria andAttribute10Between(String value1, String value2) {
            addCriterion("Attribute10 between", value1, value2, "attribute10");
            return (Criteria) this;
        }

        public Criteria andAttribute10NotBetween(String value1, String value2) {
            addCriterion("Attribute10 not between", value1, value2, "attribute10");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_video
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 08 14:55:54 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_video
     *
     * @mbggenerated Wed Mar 08 14:55:54 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}